package kernel.database.migrations.schema

import kernel.database.migrations.support.SqlLiteral

/**
 * Definicion fluida de una columna PostgreSQL.
 */
class ColumnDefinition internal constructor(
    internal val name: String,
    private val type: String
) {
    internal var isPrimaryKey = false
        private set

    private var nullable = true
    private var unique = false
    private var defaultSql: String? = null
    private var generatedSql: String? = null
    private var identitySql: String? = null

    /**
     * Marca la columna como llave primaria y la fuerza a `NOT NULL`.
     */
    fun primaryKey(): ColumnDefinition {
        isPrimaryKey = true
        nullable = false

        return this
    }

    /**
     * Alias corto estilo Laravel para `primaryKey`.
     */
    fun primary(): ColumnDefinition {
        return primaryKey()
    }

    /**
     * Marca la columna como `NOT NULL`.
     */
    fun notNull(): ColumnDefinition {
        nullable = false

        return this
    }

    /**
     * Marca la columna como nullable.
     */
    fun nullable(): ColumnDefinition {
        nullable = true

        return this
    }

    /**
     * Agrega una restriccion `UNIQUE` inline sobre la columna.
     */
    fun unique(): ColumnDefinition {
        unique = true

        return this
    }

    /**
     * Define un `DEFAULT` de texto escapado como literal SQL.
     */
    fun default(value: String): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }

        defaultSql = SqlLiteral.string(value)

        return this
    }

    /**
     * Define un `DEFAULT` numerico sin comillas.
     */
    fun default(value: Number): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }

        defaultSql = value.toString()

        return this
    }

    /**
     * Define un `DEFAULT` booleano como `TRUE` o `FALSE`.
     */
    fun default(value: Boolean): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }

        defaultSql = if (value) "TRUE" else "FALSE"

        return this
    }

    /**
     * Define `CURRENT_TIMESTAMP` como valor por defecto.
     */
    fun defaultCurrentTimestamp(): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }

        defaultSql = "CURRENT_TIMESTAMP"

        return this
    }

    /**
     * Alias estilo Laravel para `defaultCurrentTimestamp`.
     */
    fun useCurrent(): ColumnDefinition {
        return defaultCurrentTimestamp()
    }

    /**
     * Define `gen_random_uuid()` como default para UUID generados en PostgreSQL.
     */
    fun defaultGeneratedUuid(): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }

        defaultSql = "gen_random_uuid()"

        return this
    }

    /**
     * Alias expresivo para `defaultGeneratedUuid`.
     */
    fun generatedUuid(): ColumnDefinition {
        return defaultGeneratedUuid()
    }

    /**
     * Define un `DEFAULT` usando una expresion SQL sin escapar.
     */
    fun defaultRaw(expression: String): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }
        val normalizedExpression = expression.trim()

        require(normalizedExpression.isNotEmpty()) {
            "La expresion default no puede estar vacia."
        }

        defaultSql = normalizedExpression

        return this
    }

    /**
     * Declara una columna generada almacenada con `GENERATED ALWAYS AS (...) STORED`.
     */
    fun storedAs(expression: String): ColumnDefinition {
        val normalizedExpression = expression.trim()

        require(normalizedExpression.isNotEmpty()) {
            "La expresion generada no puede estar vacia."
        }
        require(defaultSql == null) {
            "Una columna generada no puede tener DEFAULT."
        }
        require(identitySql == null) {
            "Una columna generada no puede usar IDENTITY."
        }

        generatedSql = "GENERATED ALWAYS AS ($normalizedExpression) STORED"

        return this
    }

    /**
     * Declara la columna como `GENERATED ALWAYS AS IDENTITY`.
     */
    fun generatedAlwaysAsIdentity(): ColumnDefinition {
        return identity("GENERATED ALWAYS AS IDENTITY")
    }

    /**
     * Declara la columna como `GENERATED BY DEFAULT AS IDENTITY`.
     */
    fun generatedByDefaultAsIdentity(): ColumnDefinition {
        return identity("GENERATED BY DEFAULT AS IDENTITY")
    }

    /**
     * Renderiza la definicion completa de columna para `CREATE TABLE` o `ADD COLUMN`.
     */
    internal fun toSql(): String {
        val parts = mutableListOf(name, type)

        generatedSql?.let { generated ->
            parts += generated
        }

        identitySql?.let { identity ->
            parts += identity
        }

        if (!nullable) {
            parts += "NOT NULL"
        }

        if (unique) {
            parts += "UNIQUE"
        }

        defaultSql?.let { defaultValue ->
            parts += "DEFAULT $defaultValue"
        }

        return parts.joinToString(" ")
    }

    /**
     * Configura el fragmento IDENTITY y evita combinaciones no soportadas.
     */
    private fun identity(sql: String): ColumnDefinition {
        require(generatedSql == null) {
            "Una columna IDENTITY no puede ser generada."
        }

        identitySql = sql
        nullable = false

        return this
    }
}
